#!/bin/bash
# ============================================================
# Bangkok Video Processing Script for Discover Thailand
# Run from Git Bash: bash process-bangkok-clips.sh
# ============================================================

SRC="C:/Users/scott/documents/discover-thailand/raw-downloads/bangkok"
YT_DST="C:/Users/scott/documents/discover-thailand/youtube/raw"
WEB_DST="C:/Users/scott/documents/discover-thailand/public/videos/destinations"

mkdir -p "$YT_DST"
mkdir -p "$WEB_DST"

echo "============================================"
echo "STEP 1: Copy & rename 98 clips to youtube/raw"
echo "============================================"

# Hardcoded rename mapping (original -> clean name)
declare -A RENAMES=(
  ["4k-air-asia-airline-taxiing-to-gate-flying-tarmac-terminal-transportation-world-air-SBV-320050742-4K.mp4"]="bangkok-air-asia-taxiing.mp4"
  ["aerial-view-of-golden-mount-temple-wat-saket-at-night-in-bangkok-thailand-SBV-352728973-4K.mp4"]="bangkok-wat-saket-golden-mount-night-aerial.mp4"
  ["airplane-taxiing-at-bangkok-airport-SBV-352774884-4K.mp4"]="bangkok-airplane-taxiing-airport.mp4"
  ["airplane-taxiing-at-bangkok-airport-SBV-353019748-4K.mp4"]="bangkok-airplane-taxiing-airport-2.mp4"
  ["asian-street-food-delicious-food-with-seafood-fried-rice-vegetables-on-night-market-SBV-338434136-4K.mp4"]="bangkok-night-market-seafood-fried-rice.mp4"
  ["banana-display-at-floating-market-SBV-352576719-4K.mp4"]="bangkok-floating-market-banana-display.mp4"
  ["bangkok-business-district-traffic-jam-time-lapse-video-SBV-306994201-4K.mp4"]="bangkok-business-district-traffic-timelapse.mp4"
  ["bangkok-thailand-23-oct-2020-thai-travelers-do-domestic-flights-during-pandemic-eve-SBV-338842119-4K.mp4"]="bangkok-domestic-flights-terminal.mp4"
  ["bangkok-thailand-2-feb-2020-timelapse-tourist-and-local-walking-at-chinese-street-f-SBV-338522048-4K.mp4"]="bangkok-chinatown-street-timelapse.mp4"
  ["bangkok-thailand-april-1-2015-passengers-boarding-to-the-airplane-by-shuttle-bus-on-SBV-301714002-HD.mp4"]="bangkok-passengers-boarding-shuttle-bus.mp4"
  ["bangkok-thailand-march-2016-wat-phra-kaew-grand-palace-bangkok-landmark-of-thailand-SBV-307358491-HD.mp4"]="bangkok-wat-phra-kaew-grand-palace.mp4"
  ["bangkok-thailand-sunset-skyline-aerial-drone-orbit-circle-shot-city-traffic-dusk-ur-SBV-320677380-4K.mp4"]="bangkok-sunset-skyline-aerial-drone.mp4"
  ["bartender-prepares-whiskey-cocktail-with-ice-at-bangkok-bar-SBV-353361889-4K.mp4"]="bangkok-bar-whiskey-cocktail.mp4"
  ["bees-pollinating-a-lotus-flower-SBV-352732040-4K.mp4"]="bangkok-lotus-flower-bees.mp4"
  ["buddhist-monks-walking-at-a-temple-in-bangkok-thailand-temple-of-the-reclining-budd-SBV-352948231-4K.mp4"]="bangkok-monks-walking-wat-pho.mp4"
  ["cheers-with-friends-in-bangkok-bar-SBV-352437196-4K.mp4"]="bangkok-bar-cheers-friends.mp4"
  ["classic-green-passenger-train-at-bangkok-railway-platform-SBV-353450117-4K.mp4"]="bangkok-green-train-railway-platform.mp4"
  ["cocktail-gathering-in-bangkok-bar-SBV-352741949-4K.mp4"]="bangkok-bar-cocktail-gathering.mp4"
  ["colorful-tropical-fruits-display-SBV-352819667-4K.mp4"]="bangkok-tropical-fruits-display.mp4"
  ["commuters-inside-bangkok-local-train-carriage-in-motion-SBV-353456498-4K.mp4"]="bangkok-commuters-train-carriage.mp4"
  ["cooking-pad-thai-at-floating-market-SBV-352322156-4K.mp4"]="bangkok-cooking-pad-thai-floating-market.mp4"
  ["cooking-thai-crispy-coconut-pancake-with-egg-floss-traditional-dessert-street-food-SBV-326642586-4K.mp4"]="bangkok-crispy-coconut-pancake-street-food.mp4"
  ["cu-r-f-golden-buddha-statues-wat-pho-bangkok-thailand-SBV-311430287-HD.mp4"]="bangkok-golden-buddha-statues-wat-pho.mp4"
  ["damnoen-saduak-floating-markets-bangkok-thailand-southeast-asia-asia-SBV-315376004-4K.mp4"]="bangkok-damnoen-saduak-floating-market.mp4"
  ["durian-display-at-floating-market-SBV-352576724-4K.mp4"]="bangkok-floating-market-durian-display.mp4"
  ["duty-free-area-at-suvarnabhumi-airport-bangkok-thailand-south-east-asia-asia-SBV-316050722-4K.mp4"]="bangkok-suvarnabhumi-duty-free.mp4"
  ["editorial-bangkok-thailand-31-october-2015-siam-paragon-shopping-mall-fountain-with-SBV-313563149-HD.mp4"]="bangkok-siam-paragon-fountain.mp4"
  ["elephant-rides-bangkok-thailand-southeast-asia-asia-SBV-315373309-4K.mp4"]="bangkok-elephant-rides.mp4"
  ["elephant-rides-bangkok-thailand-southeast-asia-asia-SBV-315373333-4K.mp4"]="bangkok-elephant-rides-2.mp4"
  ["elevated-train-travels-through-bangkok-city-center-on-a-sunny-day-in-thailand-SBV-352786581-4K.mp4"]="bangkok-bts-elevated-train-city-center.mp4"
  ["enjoying-fiery-pork-ribs-broth-meal-SBV-352732033-4K.mp4"]="bangkok-fiery-pork-ribs-broth.mp4"
  ["enjoying-shrimp-pad-thai-in-bangkok-SBV-352740710-4K.mp4"]="bangkok-shrimp-pad-thai.mp4"
  ["enjoying-yakisoba-in-bangkok-restaurant-SBV-352972702-4K.mp4"]="bangkok-yakisoba-restaurant.mp4"
  ["fresh-lobsters-displayed-at-bangkok-street-seafood-market-SBV-352825728-4K.mp4"]="bangkok-lobsters-street-seafood-market.mp4"
  ["fruit-drink-stall-on-yaowarat-road-chinatown-bangkok-thailand-southeast-asia-asia-SBV-315376412-4K.mp4"]="bangkok-yaowarat-chinatown-fruit-drinks.mp4"
  ["grilled-bananas-at-bangkok-floating-market-SBV-352981487-4K.mp4"]="bangkok-grilled-bananas-floating-market.mp4"
  ["grilled-bananas-at-bangkok-market-SBV-352715409-4K.mp4"]="bangkok-grilled-bananas-market.mp4"
  ["grilled-beef-skewers-with-dipping-sauce-in-bangkok-eatery-SBV-352660743-4K.mp4"]="bangkok-grilled-beef-skewers.mp4"
  ["grilling-meat-street-food-crocodile-skewer-bbq-in-asian-market-exotic-delicacy-SBV-332115495-4K.mp4"]="bangkok-exotic-meat-skewers-bbq.mp4"
  ["handling-a-custard-apple-in-bangkok-SBV-352765580-4K.mp4"]="bangkok-custard-apple.mp4"
  ["hd-video-of-asian-senior-couple-travel-to-thailand-floating-market-drinking-frsh-co-SBV-306148877-HD.mp4"]="bangkok-floating-market-senior-couple.mp4"
  ["illuminated-seven-eleven-store-at-night-bangkok-thailand-12-may-2018-SBV-326649731-HD.mp4"]="bangkok-seven-eleven-night.mp4"
  ["korean-bbq-grilling-in-bangkok-restaurant-SBV-352534138-4K.mp4"]="bangkok-korean-bbq-grilling.mp4"
  ["local-people-cooking-street-food-near-wat-pho-bangkok-thailand-southeast-asia-asia-SBV-315376077-4K.mp4"]="bangkok-street-food-cooking-near-wat-pho.mp4"
  ["lumphini-park-in-bangkok-thailand-SBV-353410894-4K.mp4"]="bangkok-lumphini-park.mp4"
  ["lumpini-park-bangkok-thailand-southeast-asia-asia-SBV-315376583-4K.mp4"]="bangkok-lumpini-park-2.mp4"
  ["moving-along-the-golf-course-aerial-shot-from-madeira-SBV-311071726-4K.mp4"]="bangkok-golf-course-aerial.mp4"
  ["night-boat-on-chao-phraya-river-SBV-352678062-4K.mp4"]="bangkok-chao-phraya-river-night-boat.mp4"
  ["pad-thai-selling-at-night-market-putting-in-plate-for-tourist-in-bangkok-SBV-315314807-HD.mp4"]="bangkok-pad-thai-night-market-serving.mp4"
  ["peaceful-walkway-in-suan-luang-rama-ix-park-SBV-352536893-4K.mp4"]="bangkok-suan-luang-rama-ix-park-walkway.mp4"
  ["pedestrians-on-khao-san-road-at-dusk-bangkok-thailand-south-east-asia-asia-SBV-316050351-4K.mp4"]="bangkok-khao-san-road-dusk.mp4"
  ["phanfa-bridge-to-water-gate-canal-bangkok-thailand-southeast-asia-asia-SBV-315373608-4K.mp4"]="bangkok-phanfa-bridge-canal.mp4"
  ["pouring-spicy-thai-sauce-over-fried-fish-in-bangkok-restaurant-SBV-353605088-4K.mp4"]="bangkok-spicy-sauce-fried-fish.mp4"
  ["preparing-pineapple-baked-rice-in-bangkok-SBV-353397867-HD.mp4"]="bangkok-pineapple-baked-rice.mp4"
  ["preparing-thai-crepes-khanom-bueang-in-bangkok-thailand-SBV-306794359-4K.mp4"]="bangkok-khanom-bueang-thai-crepes.mp4"
  ["riverside-temple-of-wat-arun-temple-of-dawn-bangkok-thailand-southeast-asia-asia-SBV-315322017-4K.mp4"]="bangkok-wat-arun-riverside.mp4"
  ["roasted-chicken-at-floating-market-SBV-352300497-4K.mp4"]="bangkok-floating-market-roasted-chicken.mp4"
  ["roasting-chestnuts-in-large-metal-pan-at-bangkok-street-market-SBV-352804597-4K.mp4"]="bangkok-roasting-chestnuts-street-market.mp4"
  ["scenic-golf-course-in-bangkok-SBV-352717762-4K.mp4"]="bangkok-scenic-golf-course.mp4"
  ["serene-day-at-suan-luang-park-SBV-352401931-4K.mp4"]="bangkok-suan-luang-park-serene.mp4"
  ["serene-golf-course-in-bangkok-SBV-352741166-4K.mp4"]="bangkok-serene-golf-course.mp4"
  ["serene-walk-by-bangkok-park-pond-SBV-352515820-4K.mp4"]="bangkok-park-pond-walk.mp4"
  ["serving-spicy-thai-pork-salad-with-rice-in-bangkok-restaurant-SBV-353396513-4K.mp4"]="bangkok-spicy-pork-salad-rice.mp4"
  ["sharing-a-thai-papaya-salad-meal-SBV-352540138-4K.mp4"]="bangkok-papaya-salad-sharing.mp4"
  ["skytrain-that-follows-phloen-chit-road-bangkok-thailand-southeast-asia-asia-SBV-315373495-4K.mp4"]="bangkok-bts-skytrain-phloen-chit.mp4"
  ["slicing-roast-duck-in-bangkok-restaurant-SBV-352799588-4K.mp4"]="bangkok-roast-duck-slicing.mp4"
  ["steaming-hot-plate-of-fried-noodles-in-bangkok-street-market-SBV-353012442-4K.mp4"]="bangkok-steaming-fried-noodles-street.mp4"
  ["street-food-on-phetchaburi-road-bangkok-thailand-southeast-asia-asia-SBV-315376150-4K.mp4"]="bangkok-street-food-phetchaburi-road.mp4"
  ["street-scene-and-street-food-on-khao-san-road-bangkok-thailand-southeast-asia-asia-SBV-315373766-4K.mp4"]="bangkok-khao-san-road-street-food.mp4"
  ["street-scene-and-street-food-on-khao-san-road-bangkok-thailand-southeast-asia-asia-SBV-315373777-4K.mp4"]="bangkok-khao-san-road-street-food-2.mp4"
  ["street-vendor-slicing-crispy-pork-in-bangkok-SBV-352589243-4K.mp4"]="bangkok-crispy-pork-vendor.mp4"
  ["stroll-through-rama-ix-park-bangkok-SBV-352481613-4K.mp4"]="bangkok-rama-ix-park-stroll.mp4"
  ["sunset-golf-scene-in-bangkok-SBV-352543483-4K.mp4"]="bangkok-golf-sunset.mp4"
  ["sunset-over-thana-city-golf-course-SBV-352739871-4K.mp4"]="bangkok-thana-city-golf-sunset.mp4"
  ["sunset-relaxation-at-benjakitti-park-bangkok-SBV-352513553-4K.mp4"]="bangkok-benjakitti-park-sunset.mp4"
  ["tanghulu-at-bangkok-floating-market-SBV-352727475-4K.mp4"]="bangkok-tanghulu-floating-market.mp4"
  ["thai-food-sharing-in-bangkok-SBV-352726412-4K.mp4"]="bangkok-thai-food-sharing.mp4"
  ["thailand-aerial-bangkok-the-grand-palace-206-SBV-349306275-4K.mp4"]="bangkok-grand-palace-aerial.mp4"
  ["thailand-bangkok-april-05-2014-people-float-on-the-raft-on-the-kwai-river-also-know-SBV-304930336-HD.mp4"]="bangkok-kwai-river-raft.mp4"
  ["thailand-bangkok-april-11-2014-thai-people-and-heavy-traffic-in-bangkok-thailand-SBV-304927426-HD.mp4"]="bangkok-heavy-traffic.mp4"
  ["thailand-bangkok-april-13-2014-people-inside-international-airport-in-bangkok-thail-SBV-304927464-HD.mp4"]="bangkok-international-airport-interior.mp4"
  ["thailand-bangkok-march-30-2014-information-board-inside-arrival-hall-in-internation-SBV-304926988-HD.mp4"]="bangkok-airport-arrival-hall.mp4"
  ["thai-lunch-gathering-in-bangkok-SBV-352425229-4K.mp4"]="bangkok-thai-lunch-gathering.mp4"
  ["thai-spicy-pork-dish-with-beer-SBV-352980856-4K.mp4"]="bangkok-spicy-pork-dish-beer.mp4"
  ["thai-street-food-fried-noodle-in-tray-SBV-319935755-4K.mp4"]="bangkok-street-food-fried-noodle-tray.mp4"
  ["the-grand-palace-in-bangkok-is-a-complex-of-buildings-at-the-heart-of-thailand-SBV-352928173-4K.mp4"]="bangkok-grand-palace-complex.mp4"
  ["timelapse-food-vendors-on-khao-san-road-at-night-on-20-november-2012-in-bangkok-tha-SBV-301472554-HD.mp4"]="bangkok-khao-san-road-night-timelapse.mp4"
  ["timelapse-food-vendors-on-khao-san-road-at-night-on-20-november-2012-in-bangkok-tha-SBV-301472564-HD.mp4"]="bangkok-khao-san-road-night-timelapse-2.mp4"
  ["timelapse-food-vendors-on-khao-san-road-at-night-on-20-november-2012-in-bangkok-tha-SBV-301472580-HD.mp4"]="bangkok-khao-san-road-night-timelapse-3.mp4"
  ["tom-yum-kung-goong-with-coconut-milk-soup-local-thai-traditional-signature-dish-SBV-319803168-HD (1).mp4"]="bangkok-tom-yum-kung-soup-2.mp4"
  ["tom-yum-kung-goong-with-coconut-milk-soup-local-thai-traditional-signature-dish-SBV-319803168-HD.mp4"]="bangkok-tom-yum-kung-soup.mp4"
  ["traders-and-buyers-on-boats-at-damnoen-saduak-floating-markets-bangkok-thailand-sou-SBV-315373171-4K.mp4"]="bangkok-damnoen-saduak-traders-boats.mp4"
  ["traders-and-buyers-on-boats-at-damnoen-saduak-floating-markets-bangkok-thailand-sou-SBV-315373217-4K.mp4"]="bangkok-damnoen-saduak-traders-boats-2.mp4"
  ["variety-kind-of-thai-bbq-skewers-selling-at-local-market-SBV-309334564-HD.mp4"]="bangkok-bbq-skewers-local-market.mp4"
  ["variety-of-thai-foods-short-footages-video-montage-SBV-305057891-HD.mp4"]="bangkok-thai-foods-montage.mp4"
  ["vibrant-bangkok-street-food-market-SBV-352401799-4K.mp4"]="bangkok-vibrant-street-food-market.mp4"
  ["walking-through-bangkok-airport-terminal-SBV-352404828-4K.mp4"]="bangkok-airport-terminal-walking.mp4"
  ["ws-monks-coming-out-of-buddhist-temple-wat-pho-bangkok-thailand-SBV-311430520-HD.mp4"]="bangkok-monks-leaving-wat-pho.mp4"
)

count=0
for orig in "${!RENAMES[@]}"; do
  clean="${RENAMES[$orig]}"
  if [ -f "$SRC/$orig" ]; then
    cp "$SRC/$orig" "$YT_DST/$clean"
    echo "  [$((++count))/98] $clean"
  else
    echo "  WARNING: Not found: $orig"
  fi
done

echo ""
echo "Copied $count files to $YT_DST"
echo ""

echo "============================================"
echo "STEP 2 & 3: Select + FFmpeg compress 6 web clips"
echo "============================================"
echo ""
echo "Selected clips:"
echo "  HERO:    bangkok-sunset-skyline-aerial-drone (aerial drone sunset skyline - stunning establishing shot)"
echo "  BREAK 1: bangkok-grand-palace-aerial (aerial Grand Palace - iconic temple)"
echo "  BREAK 2: bangkok-cooking-pad-thai-floating-market (pad thai cooking at floating market - food + culture)"
echo "  BREAK 3: bangkok-khao-san-road-dusk (Khao San Road at dusk - nightlife/city energy)"
echo "  BREAK 4: bangkok-monks-walking-wat-pho (Buddhist monks at Wat Pho - cultural/spiritual)"
echo "  BREAK 5: bangkok-benjakitti-park-sunset (Benjakitti Park sunset - calm farewell)"
echo ""

# Web clip source files (using original names from raw-downloads)
declare -A WEB_CLIPS=(
  ["bangkok-hero.mp4"]="bangkok-thailand-sunset-skyline-aerial-drone-orbit-circle-shot-city-traffic-dusk-ur-SBV-320677380-4K.mp4"
  ["bangkok-break-1.mp4"]="thailand-aerial-bangkok-the-grand-palace-206-SBV-349306275-4K.mp4"
  ["bangkok-break-2.mp4"]="cooking-pad-thai-at-floating-market-SBV-352322156-4K.mp4"
  ["bangkok-break-3.mp4"]="pedestrians-on-khao-san-road-at-dusk-bangkok-thailand-south-east-asia-asia-SBV-316050351-4K.mp4"
  ["bangkok-break-4.mp4"]="buddhist-monks-walking-at-a-temple-in-bangkok-thailand-temple-of-the-reclining-budd-SBV-352948231-4K.mp4"
  ["bangkok-break-5.mp4"]="sunset-relaxation-at-benjakitti-park-bangkok-SBV-352513553-4K.mp4"
)

for output in "bangkok-hero.mp4" "bangkok-break-1.mp4" "bangkok-break-2.mp4" "bangkok-break-3.mp4" "bangkok-break-4.mp4" "bangkok-break-5.mp4"; do
  input="${WEB_CLIPS[$output]}"
  echo "Compressing: $output (from $input)..."
  ffmpeg -y -i "$SRC/$input" \
    -vf "scale=1920:-2,drawtext=text='discoverthailand.info':fontsize=32:fontcolor=white@0.8:shadowcolor=black@0.6:shadowx=2:shadowy=2:x=w-tw-20:y=h-th-20:fontfile='/Windows/Fonts/arialbd.ttf'" \
    -c:v libx264 -crf 28 -preset slow -an -movflags +faststart \
    "$WEB_DST/$output"
  echo "  Done: $(ls -lh "$WEB_DST/$output" | awk '{print $5}')"
  echo ""
done

echo "============================================"
echo "STEP 4: Results"
echo "============================================"
echo ""
echo "YouTube raw clips:"
ls "$YT_DST" | grep "^bangkok-" | wc -l
echo "files copied"
echo ""
echo "Compressed web clips:"
ls -lh "$WEB_DST/bangkok-"*
echo ""
echo "Done!"
